/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    APlayer: typeof import('./../src/components/APlayer.vue')['default']
    ArchiveCard: typeof import('./../src/components/ArchiveCard.vue')['default']
    Comment: typeof import('./../src/components/Comment.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    PostFooter: typeof import('./../src/components/PostFooter.vue')['default']
    PostHeader: typeof import('./../src/components/PostHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../src/components/Sidebar.vue')['default']
    SidebarSearch: typeof import('./../src/components/SidebarSearch.vue')['default']
  }
}
