// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    APlayer: typeof import('./../../src/components/APlayer.vue')['default']
    ArchiveCard: typeof import('./../../src/components/ArchiveCard.vue')['default']
    Header: typeof import('./../../src/components/Header.vue')['default']
    'IAntDesign:arrowLeftOutlined': typeof import('~icons/ant-design/arrow-left-outlined')['default']
    'IAntDesign:githubFilled': typeof import('~icons/ant-design/github-filled')['default']
    'ICarbon:arrowUp': typeof import('~icons/carbon/arrow-up')['default']
    'ICarbon:hazeNight': typeof import('~icons/carbon/haze-night')['default']
    'ICarbon:menu': typeof import('~icons/carbon/menu')['default']
    'ICarbon:rss': typeof import('~icons/carbon/rss')['default']
    'ICarbon:sun': typeof import('~icons/carbon/sun')['default']
    MarkdownIt: typeof import('./../../src/components/MarkdownIt.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('naive-ui')['NProgress']
    NResult: typeof import('naive-ui')['NResult']
    NTag: typeof import('naive-ui')['NTag']
    Sidebar: typeof import('./../../src/components/Sidebar.vue')['default']
    SidebarSearch: typeof import('./../../src/components/SidebarSearch.vue')['default']
  }
}

export { }
