// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    APlayer: typeof import('./../../src/components/APlayer.vue')['default']
    ArchiveCard: typeof import('./../../src/components/ArchiveCard.vue')['default']
    Comment: typeof import('./../../src/components/Comment.vue')['default']
    Header: typeof import('./../../src/components/Header.vue')['default']
    'IAntDesign:githubFilled': typeof import('~icons/ant-design/github-filled')['default']
    'ICarbon:arrowUp': typeof import('~icons/carbon/arrow-up')['default']
    'ICarbon:hazeNight': typeof import('~icons/carbon/haze-night')['default']
    'ICarbon:menu': typeof import('~icons/carbon/menu')['default']
    'ICarbon:rss': typeof import('~icons/carbon/rss')['default']
    'ICarbon:sun': typeof import('~icons/carbon/sun')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('naive-ui')['NProgress']
    NRate: typeof import('naive-ui')['NRate']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    PostFooter: typeof import('./../../src/components/PostFooter.vue')['default']
    PostHeader: typeof import('./../../src/components/PostHeader.vue')['default']
    Sidebar: typeof import('./../../src/components/Sidebar.vue')['default']
    SidebarSearch: typeof import('./../../src/components/SidebarSearch.vue')['default']
  }
}

export { }
