/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    APlayer: typeof import('./../components/APlayer.vue')['default']
    ArchiveCard: typeof import('./../components/ArchiveCard.vue')['default']
    Comment: typeof import('./../components/Comment.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    'IAntDesign:githubFilled': typeof import('~icons/ant-design/github-filled')['default']
    'ICarbon:arrowUp': typeof import('~icons/carbon/arrow-up')['default']
    'ICarbon:hazeNight': typeof import('~icons/carbon/haze-night')['default']
    'ICarbon:menu': typeof import('~icons/carbon/menu')['default']
    'ICarbon:rss': typeof import('~icons/carbon/rss')['default']
    'ICarbon:sun': typeof import('~icons/carbon/sun')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NPagination: typeof import('naive-ui')['NPagination']
    NRate: typeof import('naive-ui')['NRate']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    PostFooter: typeof import('./../components/PostFooter.vue')['default']
    PostHeader: typeof import('./../components/PostHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/Sidebar.vue')['default']
    SidebarSearch: typeof import('./../components/SidebarSearch.vue')['default']
  }
}
