name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - uses: actions/checkout@v2

      - name: install dependencies
        run: pnpm i

      - name: run lint
        run: pnpm lint

      - name: test build
        run: pnpm build

      - name: install dependencies
        run: sudo apt install tree

      - name: manually check output
        run: tree dist
